[project]
name = "adk-samples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=1.1.1",
    "python-dotenv>=1.1.0",
]
